### ISSUE TITLE
WellBuddy Custom Sensor

### ISSUE THREAD

**Issue by ChrisKraw** [ChrisKraw/CK-HomeAssistant#4]
To do:

1) Add text sensor "Status" - either "Running" "Off" - use filters https://esphome.io/components/sensor/index.html#offset-multiply

2) Add Led status when pump is running

3) Determine pump drawn down Gal/m to be used to calculate water usage per day - and other stats
https://www.cleanwaterstore.com/resource/calculators/how-to-determine-pump-flow-rate-on-systems-with-pressure-tanks/

a) This might help http://automatedhome.party/2017/03/24/current-monitor-and-water-sensor-for-sump-pump/

b) Or create custom output Sensor - http://automatedhome.party/2017/03/24/current-monitor-and-water-sensor-for-sump-pump/

c) Or custom sensor component - https://esphome.io/components/sensor/custom.html

**Comment by ChrisKraw** [comment]
Moved to its own project

**Comment by rradar** [comment]
sketch?
